import { createHash } from "node:crypto";
import { queryOne } from "@/lib/db/client";
import { AcceptInviteForm } from "./AcceptInviteForm";

export const dynamic = "force-dynamic";

const SHELL = "mx-auto flex min-h-screen max-w-[360px] flex-col justify-center px-4";

/**
 * The landing page for the one-time link generated by inviteAdmin() (see
 * src/app/admin/team/actions.ts). Not behind requireAdmin() -- see
 * src/proxy.ts's isInviteAccept carve-out -- because whoever opens this has
 * no session yet by definition. The token itself, hashed and looked up
 * here, is the only thing that authorizes setting a password.
 */
export default async function InviteAcceptPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const tokenHash = createHash("sha256").update(token).digest("hex");

  // Expiry is compared in SQL (`expires_at > now()`), not against a
  // Date.now() read in this component -- the database's clock is the one
  // source of truth for "now" here, and comparing in the query also avoids
  // an impure Date.now() call in a component body.
  const [validRow, anyRow] = await Promise.all([
    queryOne<{ email: string; purpose: string }>(
      "select email, purpose from invite_tokens where token_hash = $1 and expires_at > now()",
      [tokenHash]
    ),
    queryOne<{ email: string }>(
      "select email from invite_tokens where token_hash = $1",
      [tokenHash]
    ),
  ]);

  if (!validRow) {
    return (
      <main className={SHELL}>
        <h1 className="text-xl font-semibold tracking-tight">Link not valid</h1>
        <p className="mt-2 text-sm" style={{ color: "var(--muted)" }}>
          {anyRow
            ? "This link has expired. Ask an administrator for a new one."
            : "This link is invalid or has already been used. Ask an administrator for a new one."}
        </p>
      </main>
    );
  }
  const row = validRow;

  return (
    <main className={SHELL}>
      <h1 className="text-xl font-semibold tracking-tight">
        {row.purpose === "reset" ? "Choose a new password" : "Set your password"}
      </h1>
      <p className="mt-1 text-sm" style={{ color: "var(--muted)" }}>
        {row.purpose === "reset"
          ? "Setting a new password signs this account out everywhere else."
          : "You've been invited to One.Simple. Choose a password to finish."}
      </p>
      <AcceptInviteForm token={token} email={row.email} />
    </main>
  );
}
